print("Corona Circular")
radio_ma = float(input("Ingrese radio mayor"))
radio_me = float(input("Ingrese radio menor"))
area = 3.14 * (radio_ma ** 2 - medio_me ** 2)
print("Resultados")
print("Área: ",area)
